apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adapter-pvc.yaml
  - adapter.yaml
  - catalog.yaml
  - couchdb.yaml
  - design-system.yaml
  - graphql.yaml
  - linkedpipes-etl.yaml
  - namespace.yaml
  - public-pvc.yaml
  - public.yaml
  - solr.yaml
  - virtuoso.yaml
